### ISSUE TITLE
作者您好，问您一个问题

### ISSUE THREAD

**Issue by xiaozhangya** [GewelsJI/PNS-Net#1]
cd ./lib/PNS
python setup.py build develop
这一点安装是在什么地方呀？cd 找不到路径，谢谢！

**Comment by GewelsJI** [comment]
直接在项目目录下执行`cd ./lib/PNS`即可找到对应路径

**Comment by xiaozhangya** [comment]
作者这种github得风格太棒了，复现操作非常方便。

**Comment by GewelsJI** [comment]
感谢您的关注，我们会继续做好相关开源工作，方便社区内研究人员使用
