### ISSUE TITLE
ModuleNotFoundError: No module named 'self_cuda_backend'

### ISSUE THREAD

**Issue by GrandMountFoxc** [GewelsJI/PNS-Net#10]
作者，您好，我已经按照您在Readme中的环境配置命令配置相应环境并运行了“python setup.py build develop”命令，运行期间没有报错，但运行完成后似乎没有生成“self_cuda_backend”文件，而且代码还是会报错，下图是我这边运行后的文件结构不知道是不是我这边运行错误，如果运行正常，会在哪里生成“self_cuda_backend”文件，麻烦您解答一下，感谢！
![Snipaste_2022-04-29_15-11-50](https://user-images.githubusercontent.com/97771413/165899730-9bfd5164-b0e7-4f2c-8bb0-1d84f516f43e.png)

**Comment by johnson111788** [comment]
您好，麻煩您提供一下編譯過程的截圖以及您GCC的版本。

**Comment by GrandMountFoxc** [comment]
我的GCC版本是9.4.0，编译过程比较长，所以只截取了一部分
![Snipaste_2022-04-29_16-47-35](https://user-images.githubusercontent.com/97771413/165913563-76429062-3ce8-4ca8-8f65-44ddecf37657.png)
![Snipaste_2022-04-29_16-48-14](https://user-images.githubusercontent.com/97771413/165913571-6f16fe2d-034b-40e6-a55a-a91fc36f1e2c.png)
![Snipaste_2022-04-29_16-48-59](https://user-images.githubusercontent.com/97771413/165913577-ba5d01fc-73f9-4ac6-bdb6-221d5711a717.png)

**Comment by johnson111788** [comment]
您好，您可以參考一下 [Issues#8](https://github.com/GewelsJI/PNS-Net/issues/8)，可能會對您有幫助。

**Comment by GrandMountFoxc** [comment]
好的，感谢解答
