### ISSUE TITLE
ModuleNotFoundError: No module named 'self_cuda_backend'

### ISSUE THREAD

**Issue by sbinwuxia** [GewelsJI/PNS-Net#11]
您好，请问ModuleNotFoundError: No module named 'self_cuda_backend' 应该如何解决呢？

**Comment by GewelsJI** [comment]
可以参考一下：
https://github.com/GewelsJI/PNS-Net/issues/8
和
https://github.com/GewelsJI/PNS-Net/issues/10

感谢关注！
