### ISSUE TITLE
Some questions about the NL module

### ISSUE THREAD

**Issue by Liqq1** [GewelsJI/PNS-Net#12]
Hello
I would like to ask why it needs to redefine the backward for NL modules, instead of writing the module and using the backward in pytorch, because of the "processing" operation?
I am not familiar with custom functions and I hope you can answer this for me.

**Comment by GewelsJI** [comment]
Becasue our normalized self-attention block re-modify the naive self-attention module. In other words, our block re-define the forward process, and thus, the backward process also needs to be defined.

You could refer to the customed operation presented in the official pytorch tutorials.

Thank you again,
Ge-Peng.

**Comment by Liqq1** [comment]
> Becasue our normalized self-attention block re-modify the naive self-attention module. In other words, our block re-define the forward process, and thus, the backward process also needs to be defined.
> 
> You could refer to the customed operation presented in the official pytorch tutorials.
> 
> Thank you again, Ge-Peng.

Thank you for your reply
What I mean is that Constrained Self-Attention can also be implemented by calling the API that already exists in pytorch, now by writing your own CUDA arithmetic, is that to speed up the processing?

**Comment by GewelsJI** [comment]
Sorry for the late reply cause I missed your question. 

I haven't validated the difference between the two different modules. But I guess the answer is 'NOT'. You could write a comparison code for that. I think it is not very complicated.

Best,
Ge-Peng.
