### ISSUE TITLE
无法复现论文精度

### ISSUE THREAD

**Issue by zzzzzzpc** [GewelsJI/PNS-Net#13]
您好，我阅读了您在VPS任务上的工作，是非常优秀和solid的工作，但是我在使用您的代码复现论文结果的过程当中遇到了一些问题，在您给出的三个数据集上很难达到论文给出的指标性能（尤其是cvc-colon-300上maxIOU和maxDice指标相差将近8、9个点）。
我的训练方式参照预训练100epochs + 微调1个epoch的方式，超参的设置使用了config.py文件中给出的设置，并且在微调时候替换了pretrained的路径。

**Comment by zzzzzzpc** [comment]
三个数据集跑出来的txt文件内容如下：
**Dataset:CVC-ColonDB-300;**
(Dataset:CVC-ColonDB-300; 3 Sequence) seq_meanDic:0.739;seq_meanIoU:0.597;seq_wFm:0.732;seq_Sm:0.868;seq_meanEm:0.909;seq_MAE:0.005;seq_maxEm:0.979;seq_maxDice:0.798;seq_maxIoU:0.667;seq_meanSen:0.680;seq_maxSen:1.000;seq_meanSpe:0.995;seq_maxSpe:1.000.
(Dataset:CVC-ColonDB-300; 4 Sequence) seq_meanDic:0.868;seq_meanIoU:0.786;seq_wFm:0.861;seq_Sm:0.923;seq_meanEm:0.944;seq_MAE:0.016;seq_maxEm:0.977;seq_maxDice:0.909;seq_maxIoU:0.840;seq_meanSen:0.851;seq_maxSen:1.000;seq_meanSpe:0.990;seq_maxSpe:1.000.
(Dataset:CVC-ColonDB-300; 5 Sequence) seq_meanDic:0.562;seq_meanIoU:0.444;seq_wFm:0.465;seq_Sm:0.770;seq_meanEm:0.751;seq_MAE:0.049;seq_maxEm:0.799;seq_maxDice:0.628;seq_maxIoU:0.528;seq_meanSen:0.703;seq_maxSen:1.000;seq_meanSpe:0.958;seq_maxSpe:1.000.
(Dataset:CVC-ColonDB-300; 6 Sequence) seq_meanDic:0.902;seq_meanIoU:0.828;seq_wFm:0.882;seq_Sm:0.960;seq_meanEm:0.974;seq_MAE:0.006;seq_maxEm:0.993;seq_maxDice:0.936;seq_maxIoU:0.880;seq_meanSen:0.936;seq_maxSen:1.000;seq_meanSpe:0.992;seq_maxSpe:1.000.
(Dataset:CVC-ColonDB-300; 7 Sequence) seq_meanDic:0.383;seq_meanIoU:0.251;seq_wFm:0.204;seq_Sm:0.702;seq_meanEm:0.580;seq_MAE:0.036;seq_maxEm:0.911;seq_maxDice:0.617;seq_maxIoU:0.451;seq_meanSen:0.880;seq_maxSen:1.000;seq_meanSpe:0.961;seq_maxSpe:1.000.
(Dataset:CVC-ColonDB-300; 8 Sequence) seq_meanDic:0.896;seq_meanIoU:0.817;seq_wFm:0.877;seq_Sm:0.955;seq_meanEm:0.974;seq_MAE:0.007;seq_maxEm:0.992;seq_maxDice:0.925;seq_maxIoU:0.861;seq_meanSen:0.918;seq_maxSen:1.000;seq_meanSpe:0.992;seq_maxSpe:1.000.
(Dataset:CVC-ColonDB-300) meanDic:0.725;meanIoU:0.621;wFm:0.670;Sm:0.863;meanEm:0.855;MAE:0.020;maxEm:0.895;maxDice:0.765;maxIoU:0.664;meanSen:0.828;maxSen:1.000;meanSpe:0.981;maxSpe:1.000.

**Dataset:CVC-ClinicDB-612-Valid**
(Dataset:CVC-ClinicDB-612-Valid; 11 Sequence) seq_meanDic:0.869;seq_meanIoU:0.780;seq_wFm:0.846;seq_Sm:0.920;seq_meanEm:0.948;seq_MAE:0.030;seq_maxEm:0.974;seq_maxDice:0.898;seq_maxIoU:0.818;seq_meanSen:0.877;seq_maxSen:1.000;seq_meanSpe:0.979;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Valid; 15 Sequence) seq_meanDic:0.922;seq_meanIoU:0.861;seq_wFm:0.922;seq_Sm:0.964;seq_meanEm:0.981;seq_MAE:0.007;seq_maxEm:0.996;seq_maxDice:0.951;seq_maxIoU:0.907;seq_meanSen:0.915;seq_maxSen:1.000;seq_meanSpe:0.993;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Valid; 17 Sequence) seq_meanDic:0.777;seq_meanIoU:0.655;seq_wFm:0.716;seq_Sm:0.905;seq_meanEm:0.913;seq_MAE:0.013;seq_maxEm:0.976;seq_maxDice:0.822;seq_maxIoU:0.709;seq_meanSen:0.916;seq_maxSen:1.000;seq_meanSpe:0.985;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Valid; 2 Sequence) seq_meanDic:0.825;seq_meanIoU:0.725;seq_wFm:0.788;seq_Sm:0.932;seq_meanEm:0.928;seq_MAE:0.004;seq_maxEm:0.984;seq_maxDice:0.897;seq_maxIoU:0.820;seq_meanSen:0.843;seq_maxSen:1.000;seq_meanSpe:0.993;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Valid; 4 Sequence) seq_meanDic:0.867;seq_meanIoU:0.780;seq_wFm:0.834;seq_Sm:0.931;seq_meanEm:0.951;seq_MAE:0.013;seq_maxEm:0.977;seq_maxDice:0.901;seq_maxIoU:0.830;seq_meanSen:0.934;seq_maxSen:1.000;seq_meanSpe:0.985;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Valid) meanDic:0.852;meanIoU:0.760;wFm:0.821;Sm:0.930;meanEm:0.944;MAE:0.013;maxEm:0.971;maxDice:0.890;maxIoU:0.811;meanSen:0.897;maxSen:1.000;meanSpe:0.987;maxSpe:1.000.

**Dataset:CVC-ClinicDB-612-Test**
(Dataset:CVC-ClinicDB-612-Test; 0 Sequence) seq_meanDic:0.457;seq_meanIoU:0.332;seq_wFm:0.466;seq_Sm:0.663;seq_meanEm:0.582;seq_MAE:0.150;seq_maxEm:0.769;seq_maxDice:0.604;seq_maxIoU:0.461;seq_meanSen:0.341;seq_maxSen:1.000;seq_meanSpe:0.993;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Test; 16 Sequence) seq_meanDic:0.877;seq_meanIoU:0.795;seq_wFm:0.876;seq_Sm:0.925;seq_meanEm:0.950;seq_MAE:0.019;seq_maxEm:0.980;seq_maxDice:0.919;seq_maxIoU:0.856;seq_meanSen:0.841;seq_maxSen:1.000;seq_meanSpe:0.991;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Test; 24 Sequence) seq_meanDic:0.921;seq_meanIoU:0.859;seq_wFm:0.905;seq_Sm:0.948;seq_meanEm:0.968;seq_MAE:0.020;seq_maxEm:0.983;seq_maxDice:0.945;seq_maxIoU:0.898;seq_meanSen:0.945;seq_maxSen:1.000;seq_meanSpe:0.984;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Test; 6 Sequence) seq_meanDic:0.951;seq_meanIoU:0.911;seq_wFm:0.947;seq_Sm:0.972;seq_meanEm:0.982;seq_MAE:0.011;seq_maxEm:0.994;seq_maxDice:0.972;seq_maxIoU:0.947;seq_meanSen:0.964;seq_maxSen:1.000;seq_meanSpe:0.989;seq_maxSpe:1.000.
(Dataset:CVC-ClinicDB-612-Test; 7 Sequence) seq_meanDic:0.832;seq_meanIoU:0.769;seq_wFm:0.821;seq_Sm:0.917;seq_meanEm:0.943;seq_MAE:0.012;seq_maxEm:0.972;seq_maxDice:0.863;seq_maxIoU:0.820;seq_meanSen:0.847;seq_maxSen:1.000;seq_meanSpe:0.926;seq_maxSpe:0.982.
(Dataset:CVC-ClinicDB-612-Test) meanDic:0.807;meanIoU:0.733;wFm:0.803;Sm:0.885;meanEm:0.885;MAE:0.042;maxEm:0.911;maxDice:0.835;maxIoU:0.769;meanSen:0.788;maxSen:1.000;meanSpe:0.977;maxSpe:0.986.

**Comment by HuiqianLi** [comment]
同样有这个问题，自己训练的评价指标未能达到已给模型的效果，借楼麻烦问一下，作者训练用的超参数：类似batchsize是config.py里面默认的值吗？还有作者训练时用的单卡还是多卡呀？冒昧打扰了。

**Comment by zzzzzzpc** [comment]
> 同样有这个问题，自己训练的评价指标未能达到已给模型的效果，借楼麻烦问一下，作者训练用的超参数：类似batchsize是config.py里面默认的值吗？还有作者训练时用的单卡还是多卡呀？冒昧打扰了。

我暂时还没有解决这个无法到达精度这个问题，我认为应该是和config.py当中一致的，作者训练应该是在单卡RTX 2080。

**Comment by Moqixis** [comment]
> 

好的！谢谢你

**Comment by HuiqianLi** [comment]
> > 同样有这个问题，自己训练的评价指标未能达到已给模型的效果，借楼麻烦问一下，作者训练用的超参数：类似batchsize是config.py里面默认的值吗？还有作者训练时用的单卡还是多卡呀？冒昧打扰了。
> 
> 我暂时还没有解决这个无法到达精度这个问题，我认为应该是和config.py当中一致的，作者训练应该是在单卡RTX 2080。

好的！谢谢你

**Comment by GewelsJI** [comment]
Hi, @Moqixis @zzzzzzpc 

I merge the response in another issue. I hope the answer helps you guys a lot.

Best,
Ge-Peng.
