### ISSUE TITLE
提示缺少cuda.h如何解决

### ISSUE THREAD

**Issue by Yaobaobei** [GewelsJI/PNS-Net#15]
在生成编译文件时提醒我缺少gcc，并且提示我缺少cuda.h,但是我的cuda是正常安装了10.1版本的，而且也是正常安装gcc的。如下所示，请问该如何解决？
(PNSNet) yao@yao-System-Product-Name:/home/PNS-Net-main/lib/PNS$ python setup.py build develop
running build
running build_ext
building 'self_cuda_backend' extension
gcc -pthread -B /home/yao/anaconda3/envs/PNSNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yao/anaconda3/envs/PNSNet/lib/python3.6/site-packages/torch/include -I/home/yao/anaconda3/envs/PNSNet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/yao/anaconda3/envs/PNSNet/lib/python3.6/site-packages/torch/include/TH -I/home/yao/anaconda3/envs/PNSNet/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/yao/anaconda3/envs/PNSNet/include/python3.6m -c PNS_Module/sa_ext.cpp -o build/temp.linux-x86_64-3.6/PNS_Module/sa_ext.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=self_cuda_backend -D_GLIBCXX_USE_CXX11_ABI=1
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from PNS_Module/sa_ext.cpp:3:0:
PNS_Module/utils.h:6:10: fatal error: cuda.h: 没有那个文件或目录
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by johnson111788** [comment]
您好，

是否可以麻烦您提供您的gcc版本。另外，请您提供一下nvidia-smi以及nvcc -V所输出的版本。谢谢您！

**Comment by Yaobaobei** [comment]
您好，问题已经解决（重装了一下系统），但也不知道为什么解决的，给您添麻烦了

**Comment by johnson111788** [comment]
好的，如果您还有类似问题可以查看：https://github.com/GewelsJI/PNS-Net/issues/8。
