### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by zzgzzgz** [GewelsJI/PNS-Net#16]
您好,请问这个是怎么回事
/PNS-Net-main/lib/PNS/self_cuda_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKS

**Comment by johnson111788** [comment]
您好，請問這是什麼？ 麻煩描述清楚，謝謝

**Comment by johnson111788** [comment]
@zzgzzgz 

您好，bug问题能够详细一下环境和出错原因，这样方便我们给您提供合理建议。

另外，类似的问题可以参考一下：https://github.com/GewelsJI/PNS-Net/issues/8 和 https://github.com/GewelsJI/PNS-Net/issues/10

祝好！
