### ISSUE TITLE
关于训练模型的问题

### ISSUE THREAD

**Issue by Zachary-Hwang** [GewelsJI/PNS-Net#17]
Remember to configure the pretrain_state_dict in config.py for different training stages 这个是什么文件？可以提供一下吗？

**Comment by GewelsJI** [comment]
Hi, please use this file: https://anu365-my.sharepoint.com/:u:/g/personal/u7248002_anu_edu_au/ESCsQ6-dj7xMq7Qn9jo-ieoBeAcykgZRqg1naX8zaziiTw?e=sjQbV7

**Comment by Zachary-Hwang** [comment]
thanks for your answer，but are you sure is it？：
Traceback (most recent call last):
  File "MyTrain_Pretrain.py", line 93, in <module>
    model.load_backbone(torch.load(config.pretrain_state_dict, map_location=torch.device('cpu')), logging)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /hy-tmp/PNS/pnsnet-pretrained-checkpoint.pth is a zip archive (did you mean to use torch.jit.load()?)

**Comment by GewelsJI** [comment]
It looks like you are using higher PyTorch version. Please google this error and do some modifications on loading checkpoint.

**Comment by Zachary-Hwang** [comment]
fine，thank you for your answer

**Comment by GewelsJI** [comment]
welcome

**Comment by 19558986775** [comment]
> Hi, please use this file: https://anu365-my.sharepoint.com/:u:/g/personal/u7248002_anu_edu_au/ESCsQ6-dj7xMq7Qn9jo-ieoBeAcykgZRqg1naX8zaziiTw?e=sjQbV7

您好，这个链接失效了，可以发一下新的嘛

**Comment by GewelsJI** [comment]
这个是哪一个文件的链接？我来更新一下 @19558986775

**Comment by 19558986775** [comment]
> 这个是哪一个文件的链接？我来更新一下 @19558986775
![image](https://github.com/GewelsJI/PNS-Net/assets/65281086/e3050081-5474-4559-8387-b81d24b97274)
您好，是这个文件

**Comment by 19558986775** [comment]
> > 这个是哪一个文件的链接？我来更新一下 @19558986775
> > ![image](https://user-images.githubusercontent.com/65281086/281292742-e3050081-5474-4559-8387-b81d24b97274.png)
> > 您好，是这个文件

您好，your_pretrain_pth这个文件可以发一下嘛

**Comment by GewelsJI** [comment]
Please use this checkpoint as pre-trained state: https://drive.google.com/file/d/1Ip_XF4q00bZLvrxettvU0IgcwST-RMSM/view?usp=sharing

**Comment by 19558986775** [comment]
> Please use this checkpoint as pre-trained state: https://drive.google.com/file/d/1Ip_XF4q00bZLvrxettvU0IgcwST-RMSM/view?usp=sharing

这个是原来代码torch1.1.0环境生成的嘛，load出错，原来代码带的其他的pth文件load没有问题
