### ISSUE TITLE
执行setup.py报错问题

### ISSUE THREAD

**Issue by 19558986775** [GewelsJI/PNS-Net#19]
![14dabba700a479753e145aa0d51d596](https://github.com/GewelsJI/PNS-Net/assets/65281086/f8cf06f7-dba5-4cfb-a4f8-cda435dcfee8)
![dc310c7c18e9b6c18a946343031f30b](https://github.com/GewelsJI/PNS-Net/assets/65281086/577b3c91-2f7f-4117-b293-6d12ce626a80)
您好，打扰一下，想问一下我在执行setup.py时出现如图所示错误可能是什么原因呢，python3.6，cuda12.0，cudatoolkit=10.0

**Comment by GewelsJI** [comment]
您好，cuda版本可能太高了，需要重新构建basic cuda版本

**Comment by 19558986775** [comment]
![242aecee663438cbf7cbae5373aafc1](https://github.com/GewelsJI/PNS-Net/assets/65281086/70b06fe1-9efd-4ca1-a75a-167e429158f1)
![e6006c317cac3548a2508b93a57c80d](https://github.com/GewelsJI/PNS-Net/assets/65281086/f80a3a6c-01d7-46bb-81fe-27130da903d5)
谢谢您，我将cuda降为11.4后错误变成这样了，想向您请教一下可能是何原因，多有打扰，甚是抱歉，还请见谅。

**Comment by 19558986775** [comment]
> 您好，cuda版本可能太高了，需要重新构建basic cuda版本

再次感谢您，更换cuda11.4版本后的新遇到的问题已经解决，谢谢您的耐心解答

**Comment by Frank-Cai0709** [comment]
> > 您好，cuda版本可能太高了，需要重新构建basic cuda版本
> 
> 再次感谢您，更换cuda11.4版本后的新遇到的问题已经解决，谢谢您的耐心解答

你好，请问更换版本后新遇到的问题是如何解决的呢》我也遇到了相同的问题，感谢。

**Comment by zxlzhangxiaolan** [comment]
> > > 您好，cuda版本可能太高了，需要重新构建basic cuda版本
> > 
> > 
> > 再次感谢您，更换cuda11.4版本后的新遇到的问题已经解决，谢谢您的耐心解答
> 
> 你好，请问更换版本后新遇到的问题是如何解决的呢》我也遇到了相同的问题，感谢。

您好，请问解决了吗
