### ISSUE TITLE
训练技巧和数据集的分配

### ISSUE THREAD

**Issue by forestlin7** [GewelsJI/PNS-Net#6]
您好，我最近有关注你们的工作，十分地出色！但是我遇到了一些问题，首先是我使用了你们的方法，无法达到你们的精度，我想问问您有没有使用一些tricks，还有您们的工作会再更新pytorch版本吗？下一个疑问是，对于您们的数据集的划分还是存在一些困惑，IVPS-TrainSet这个数据集是不是没有用到？验证集和测试集是用相同的吗？还是怎么去处理？
         期待您的回复，谢谢

**Comment by GewelsJI** [comment]
@forestlin7 
感谢您的关注

IVPS-TrainSet代表的是Image和Video数据集混合后的数据集，用于预训练阶段。由于Video数据和标注的获取往往需要很高的代价，这个阶段在VOS领域中同样应用广泛且是必要的，有助于提升网络学习到更多的视觉信息表征，防止网络的过拟合。

整个参数更新过程中需要保证测试集合是unseen的就可以了，数据集层面我们没有过多的处理，除了数据增强以外：

```python
trsf_main = Compose_imglabel([
        Resize(config.size[0], config.size[1]),
        Random_crop_Resize(15),
        Random_horizontal_flip(0.5),
        toTensor(),
        Normalize(statistics["mean"], statistics["std"])
    ])
```

注意：两个步骤需要紧密配合，预训练阶段需要训练直至收敛，视频数据集微调阶段也是如此。

祝好！
