### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by cslg-z** [GewelsJI/PNS-Net#7]
ModuleNotFoundError: No module named 'self_cuda_backend'
工程需要 self_cuda_backend 文件吧，谢谢解惑！

**Comment by johnson111788** [comment]
您好，此模块需要先进行编译后方可生成文件供调用。操作如下：
```
cd ./lib/PNS
python setup.py build develop
```
具体信息请参见[README.md](https://github.com/GewelsJI/PNS-Net#31-trainingtesting)文件。

谢谢您对我们工作的兴趣，有任何问题欢迎咨询。

**Comment by cslg-z** [comment]
感谢！谢谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GewelsJI/PNS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GewelsJI/PNS-Net] 缺少文件 (Issue #7)





 
您好，此模块需要先进行编译后方可生成文件供调用。操作如下：
 cd ./lib/PNS python setup.py build develop  
具体信息请参见README.md文件。
 
谢谢您对我们工作的兴趣，有任何问题欢迎咨询。
