### ISSUE TITLE
想问一下怎么提高代码cuda使用版本

### ISSUE THREAD

**Issue by VictorWylde** [GewelsJI/PNS-Net#8]
看到应该跟CUDAExtension之类的有关，请问应该修改，非常感谢

**Comment by johnson111788** [comment]
您好，本代码在不同cuda版本的服务器上建议使用docker以避免代码的改动。可以使用此[nvidia/cuda](https://hub.docker.com/layers/nvidia/cuda/10.1-cudnn7-devel-ubuntu16.04/images/sha256-71ea87ad4ca047abd0a6854872e852e9d0aeadc0f6cd9fc8b6f01cfaf8f209da?context=explore)镜像，具体命令参照如下：

`docker pull nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04`

`docker run -it --gpus all --shm-size YOUR_GPU_SIZE --name=YOUR_CONTAINER_NAME -v LOCAL_PATH:DOCKER_PATH nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 /bin/bash `

谢谢您对我们工作的兴趣，有任何问题欢迎咨询。

**Comment by suyanzhou626** [comment]
> 您好，本代码在不同cuda版本的服务器上建议使用docker以避免代码的改动。可以使用此[nvidia/cuda](https://hub.docker.com/layers/nvidia/cuda/10.1-cudnn7-devel-ubuntu16.04/images/sha256-71ea87ad4ca047abd0a6854872e852e9d0aeadc0f6cd9fc8b6f01cfaf8f209da?context=explore)镜像，具体命令参照如下：
> 
> `docker pull nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04`
> 
> `docker run -it --gpus all --shm-size YOUR_GPU_SIZE --name=YOUR_CONTAINER_NAME -v LOCAL_PATH:DOCKER_PATH nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 /bin/bash `
> 
> 谢谢您对我们工作的兴趣，有任何问题欢迎咨询。

Our server environment and some python packages are built on CUDA 11.X. Do you know how to improve the compatibility of CUDA versions?
Thank you.

**Comment by VictorWylde** [comment]
> 
你可以试试我的教程，或许能有所帮助，https://blog.csdn.net/Victor_HUST/article/details/123411685

**Comment by VictorWylde** [comment]
> > 您好，本代码在不同cuda版本的服务器上建议使用docker以避免代码的改动。可以使用此[nvidia/cuda](https://hub.docker.com/layers/nvidia/cuda/10.1-cudnn7-devel-ubuntu16.04/images/sha256-71ea87ad4ca047abd0a6854872e852e9d0aeadc0f6cd9fc8b6f01cfaf8f209da?context=explore)镜像，具体命令参照如下：
> > `docker pull nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04`
> > `docker run -it --gpus all --shm-size YOUR_GPU_SIZE --name=YOUR_CONTAINER_NAME -v LOCAL_PATH:DOCKER_PATH nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 /bin/bash `
> > 谢谢您对我们工作的兴趣，有任何问题欢迎咨询。
> 
> Our server environment and some python packages are built on CUDA 11.X. Do you know how to improve the compatibility of CUDA versions? Thank you.

你可以试试我的教程，或许能有所帮助，https://blog.csdn.net/Victor_HUST/article/details/123411685

**Comment by suyanzhou626** [comment]
> > > 您好，本代码在不同cuda版本的服务器上建议使用docker以避免代码的改动。可以使用此[nvidia/cuda](https://hub.docker.com/layers/nvidia/cuda/10.1-cudnn7-devel-ubuntu16.04/images/sha256-71ea87ad4ca047abd0a6854872e852e9d0aeadc0f6cd9fc8b6f01cfaf8f209da?context=explore)镜像，具体命令参照如下：
> > > `docker pull nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04`
> > > `docker run -it --gpus all --shm-size YOUR_GPU_SIZE --name=YOUR_CONTAINER_NAME -v LOCAL_PATH:DOCKER_PATH nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 /bin/bash `
> > > 谢谢您对我们工作的兴趣，有任何问题欢迎咨询。
> > 
> > 
> > Our server environment and some python packages are built on CUDA 11.X. Do you know how to improve the compatibility of CUDA versions? Thank you.
> 
> 你可以试试我的教程，或许能有所帮助，https://blog.csdn.net/Victor_HUST/article/details/123411685

感谢，我看了你的是在docker上操作的么，我的是cuda 11.0，我发现改成python=3.6后，build成功了，但是提示找到不到"self_cuda_backend", 如下图所示，
![image](https://user-images.githubusercontent.com/37359271/163978898-e7a94dc1-dc4e-48f6-8c1c-9d540708347a.png)
老哥，知道怎么解决么？

**Comment by johnson111788** [comment]
> 

您好，这个部分可能是您旧的编译结果没有清空。需要麻烦您将旧的编译结果（即：./build、./self_cuda.egg-info和self_cuda_backend.cpython-36m-x86_64-linux-gnu.so）删除后再重新编译。

**Comment by 19558986775** [comment]
![14dabba700a479753e145aa0d51d596](https://github.com/GewelsJI/PNS-Net/assets/65281086/bd601565-df1b-4aed-bf8a-e15019ca22fe)

**Comment by 19558986775** [comment]
![14dabba700a479753e145aa0d51d596](https://github.com/GewelsJI/PNS-Net/assets/65281086/5fac5ac4-7a18-42a4-a69a-3f6462a24f6c)
![dc310c7c18e9b6c18a946343031f30b](https://github.com/GewelsJI/PNS-Net/assets/65281086/4f52a936-ad0c-4f58-ac59-6e412e46eadc)
您好，请问一下，我在执行python setup.py时出现图示错误，想问一下可能是什么情况呢，cuda10.0，python3.6，

**Comment by VictorWylde** [comment]
你好，请按照教程修改即可
解决某些深度学习代码使用了cpp_extension，CUDAExtension编译了代码可能存在的运行环境版本过低问题，进行cuda和pytorch的运行环境升级-CSDN博客


王拓&nbsp;华中科技大学
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GewelsJI/PNS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月3日(星期五) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GewelsJI/PNS-Net] 想问一下怎么提高代码cuda使用版本 (Issue #8)





 

 
 您好，请问一下，我在执行python setup.py时出现图示错误，想问一下可能是什么情况呢，cuda10.0，python3.6，
