### ISSUE TITLE
从头训练没有达到论文中的精度

### ISSUE THREAD

**Issue by liaooninghongpeng** [GewelsJI/PNS-Net#9]
作者您好，我用您的代码从头训练但是测试结果并没有达到论文中给的精度，尤其在CVC-ColonDB-300数据集上，精度会差将近10个百分点，请问这是怎么回事呢，方便邮箱沟通一下吗

**Comment by GewelsJI** [comment]
有使用”预训练+微调“过程吗？

**Comment by liaooninghongpeng** [comment]
您好，我先用预训练训练100个epoch，然后微调阶段1个epoch，我看代码发现有点歧义，不知道预训练阶段batch size设置的是4还是20，我都试了，但是二者结果都达不到论文水平，尤其CVC-ColonDB-300这个数据集，差了将近10来个百分点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GewelsJI/PNS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 上午9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GewelsJI/PNS-Net] 从头训练没有达到论文中的精度 (Issue #9)





 
有使用”预训练+微调“过程吗？

**Comment by GewelsJI** [comment]
你好，我没能具体深入到你的训练过程，我猜测会有两个原因：数据和代码层面是否能够对齐

**Comment by GewelsJI** [comment]
你好，

预训练是20BS，微调是4BS。不知道是哪个指标会差距如此大？

抱歉我未能深入到你的训练过程，预训练我猜测会有两个

1、数据和训练参数是否ready到与我们实验对齐的状态；
2、双阶段的训练过程对于预训练阶段的依赖程度比较高，请确保能够训练到最优状态，再去微调，方可复现出性能。

NOTE：在MICCAI-2021工作中，受限于带有标注视频数据集的规模影响，我们不得不采取双阶段的训练技巧去确保获取到满意的时空表征。可以参考一下我们最新的[VPS工作](https://github.com/GewelsJI/VPS)，提供了一个大规模的VPS数据集，无需两阶段训练技巧，直接单阶段可以训练到SOTA。

祝好！

**Comment by liaooninghongpeng** [comment]
您好，您说的数据和训练参数是否ready到与我们实验对齐的状态具体是什么意思，我完全按照源码的参数并未进行修改，附件是代码config.py截图
,在预训练阶段，我的config.pretrain_state_dict设置为None，然后微调阶段，我将它设置为第100个epoch的权重所在位置。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GewelsJI/PNS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GewelsJI/PNS-Net] 从头训练没有达到论文中的精度 (Issue #9)





 
你好，
 
预训练是20BS，微调是4BS。不知道是哪个指标会差距如此大？
 
抱歉我未能深入到你的训练过程，预训练我猜测会有两个
 
1、数据和训练参数是否ready到与我们实验对齐的状态；
 2、双阶段的训练过程对于预训练阶段的依赖程度比较高，请确保能够训练到最优状态，再去微调，方可复现出性能。
 
NOTE：在MICCAI-2021工作中，受限于带有标注视频数据集的规模影响，我们不得不采取双阶段的训练技巧去确保获取到满意的时空表征。可以参考一下我们最新的VPS工作，提供了一个大规模的VPS数据集，无需两阶段训练技巧，直接单阶段可以训练到SOTA。
 
祝好！

**Comment by liaooninghongpeng** [comment]
> 有使用”预训练+微调“过程吗？

有的，您说的数据和训练参数是否ready到与我们实验对齐的状态具体是什么意思，我完全按照源码的参数并未进行修改
,在预训练阶段，我的config.pretrain_state_dict设置为None，然后微调阶段，我将它设置为第100个epoch的权重所在位置。

**Comment by liaooninghongpeng** [comment]
您好，您说的数据和训练参数是否ready到与我们实验对齐的状态具体是什么意思，我完全按照源码的参数并未进行修改，附件是代码config.py截图
,在预训练阶段，我的config.pretrain_state_dict设置为None，然后微调阶段，我将它设置为第100个epoch的权重所在位置。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GewelsJI/PNS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GewelsJI/PNS-Net] 从头训练没有达到论文中的精度 (Issue #9)





 
你好，
 
预训练是20BS，微调是4BS。不知道是哪个指标会差距如此大？
 
抱歉我未能深入到你的训练过程，预训练我猜测会有两个
 
1、数据和训练参数是否ready到与我们实验对齐的状态；
 2、双阶段的训练过程对于预训练阶段的依赖程度比较高，请确保能够训练到最优状态，再去微调，方可复现出性能。
 
NOTE：在MICCAI-2021工作中，受限于带有标注视频数据集的规模影响，我们不得不采取双阶段的训练技巧去确保获取到满意的时空表征。可以参考一下我们最新的VPS工作，提供了一个大规模的VPS数据集，无需两阶段训练技巧，直接单阶段可以训练到SOTA。
 
祝好！

**Comment by GewelsJI** [comment]
@liaooninghongpeng 你好，

请先提供一下你的测评txt，随后我安排一位同学跟你具体对接一下

祝好！

**Comment by liaooninghongpeng** [comment]
附件是我的测评结果，然后就麻烦找一位同学和我对接下啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GewelsJI/PNS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GewelsJI/PNS-Net] 从头训练没有达到论文中的精度 (Issue #9)





 
@liaooninghongpeng 你好，
 
请先提供一下你的测评txt，随后我安排一位同学跟你具体对接一下
 
祝好！

**Comment by GewelsJI** [comment]
@liaooninghongpeng 

github上看不到你的附件，把代码和附件打包发到我邮箱（gepengai.ji@gmail.com）

**Comment by GewelsJI** [comment]
问题暂时关闭，如果后续问题可以随时开启，或者邮箱联系我们。

**Comment by zzzzzzpc** [comment]
我也遇到了同样的问题，尤其在CVC-ColonDB-300上与论文指标差距将近10个点（maxDice和maxIOU），我采用了论文中的设置的超参设置，不知道是哪里出了问题呢，无法复现出论文的结果。

**Comment by GewelsJI** [comment]
I find some similar issues (such as #14 and #13) and re-organize the answer in #14. I hope this answer may help you guys a lot.
